In [1]:
from src import Extractor

In [4]:
TABLE_NAME="works4cdp_assay"
SAMPLE_ID=24 #Concentrado final de courier cobre

db_config = {
    'user': 'myuser', 
    'password': 'mypassword', 
    'host': 'localhost', 
    'port': '5432', 
    'dbname': 'mydb'
}

In [8]:
datos = Extractor(table_name=TABLE_NAME, **db_config)
df_columnas = datos.get_head()
df_columnas

WARNING:  database "mydb" has no actual collation version, but a version was recorded

    column_name               data_type is_nullable
0            id                  bigint          NO
1          date                    date         YES
2          time  time without time zone         YES
3      instance                 integer         YES
4          n2cu                 integer         YES
5          n1fe                 integer         YES
6        n5ech5                 integer         YES
7          n4mo                 integer         YES
8          n3zn                 integer         YES
9          n6sc                 integer         YES
10          pFe        double precision         YES
11          pCu        double precision         YES
12          pZn        double precision         YES
13          pMo        double precision         YES
14         pIns        double precision         YES
15         pSol        double precision         YES
16         tara        double precision         YES
17      tweight        double precision         YES
18      dweight        double precision         YES
19      pweight        double precision         YES
20  chemical_id                 integer         YES
21         a1fe        double precision         YES
22         a4mo        double precision         YES
23         a2cu        double precision         YES
24         a3zn        double precision         YES
25         a5a5        double precision         YES
26    meta_user       character varying         YES
27         turn       character varying         YES
28    sample_id                  bigint         YES
29        a6sol        double precision         YES
30         a7a7        double precision         YES
31       n7ech7                 integer         YES
32     userp_id                  bigint         YES

In [6]:
df_intensidad = datos.get_intensity(SAMPLE_ID)
df_intensidad.head()

         date      time    instance   n1fe  ...  n4mo  n5ech5  n6sc n7ech7
0  2025-12-03  11:01:00  1764777025  33558  ...  1690    None  1783   None
1  2025-12-01  11:04:20  1764604983  30953  ...  2667    None  1778   None
2  2025-12-01  11:01:46  1764604638  31900  ...  2587    None  1756   None
3  2025-11-28  12:29:52  1764349910  37782  ...  1812    None  1646   None
4  2025-11-26  11:11:58  1764173370  37364  ...  2409    None  1728   None

[5 rows x 10 columns]